# 50 food items with calorie values (per 100g or per item as noted)
FOOD_CALORIES_DATABASE = {
    "apple": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 95}],
    "banana": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 105}],
    "orange": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 62}],
    "pear": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 100}],
    "grapes": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 69}],
    "strawberry": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 32}],
    "blueberry": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 57}],
    "watermelon": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 30}],
    "pineapple": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 50}],
    "kiwi": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 42}],
    "mango": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 150}],
    "peach": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 59}],
    "plum": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 30}],
    "cherry": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 50}],
    "apricot": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 17}],
    "carrot": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 41}],
    "potato": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 77}],
    "tomato": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 22}],
    "cucumber": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 16}],
    "lettuce": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 15}],
    "broccoli": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 34}],
    "cauliflower": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 25}],
    "spinach": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 23}],
    "onion": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 40}],
    "garlic": [{"unit_name": "clove", "default_quantity": 1, "calories_per_unit": 4}],
    "egg": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 68}],
    "chicken breast": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 165}],
    "beef": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 250}],
    "lamb": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 294}],
    "salmon": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 208}],
    "tuna": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 132}],
    "shrimp": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 99}],
    "rice": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 130}],
    "bread": [{"unit_name": "slice", "default_quantity": 1, "calories_per_unit": 80}],
    "pasta": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 131}],
    "pizza": [{"unit_name": "slice", "default_quantity": 1, "calories_per_unit": 285}],
    "hamburger": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 250}],
    "hot dog": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 150}],
    "cheese": [{"unit_name": "100g", "default_quantity": 1, "calories_per_unit": 402}],
    "milk": [{"unit_name": "cup", "default_quantity": 1, "calories_per_unit": 122}],
    "yogurt": [{"unit_name": "cup", "default_quantity": 1, "calories_per_unit": 59}],
    "butter": [{"unit_name": "tbsp", "default_quantity": 1, "calories_per_unit": 102}],
    "olive oil": [{"unit_name": "tbsp", "default_quantity": 1, "calories_per_unit": 119}],
    "sugar": [{"unit_name": "tsp", "default_quantity": 1, "calories_per_unit": 16}],
    "honey": [{"unit_name": "tbsp", "default_quantity": 1, "calories_per_unit": 64}],
    "almonds": [{"unit_name": "10 nuts", "default_quantity": 1, "calories_per_unit": 70}],
    "walnuts": [{"unit_name": "10 halves", "default_quantity": 1, "calories_per_unit": 98}],
    "peanut butter": [{"unit_name": "tbsp", "default_quantity": 1, "calories_per_unit": 94}],
    "potato chips": [{"unit_name": "28g", "default_quantity": 1, "calories_per_unit": 152}],
    "chocolate": [{"unit_name": "piece", "default_quantity": 1, "calories_per_unit": 50}],
    "ice cream": [{"unit_name": "scoop", "default_quantity": 1, "calories_per_unit": 137}],
    "cookie": [{"unit_name": "item", "default_quantity": 1, "calories_per_unit": 78}],
    "cake": [{"unit_name": "slice", "default_quantity": 1, "calories_per_unit": 235}],
}
