"""add unique constraint on long_url

Revision ID: 92b4b01bb4f8
Revises: 98346e95033b
Create Date: 2026-08-30 15:18:53.743943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92b4b01bb4f8'
down_revision: Union[str, None] = '98346e95033b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'urls', ['long_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='unique')
    # ### end Alembic commands ###
